---
title: Turtley Amazing
hero_image: afbeeldingen / banner.png
description: In this resource you will take your first steps with the programming language Python
original_url: https://raspberrypi.org/learning/turtley-amazing
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: Python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Is it art, maths, or computer science?
  - 
    title: Drawing a line
  - 
    title: Draaien
  - 
    title: Changing colours
  - 
    title: Repetition
  - 
    title: Better spirals
  - 
    title: Loopy colours
  - 
    title: Modulo to the rescue
  - 
    title: Enormous lists
  - 
    title: Alles bij elkaar brengen
  - 
    title: Wat nu?
