---
title: Turtley Amazing
hero_image: images/banner.png
description: In this resource you will take your first steps with the programming
  language Python
original_url: https://raspberrypi.org/learning/turtley-amazing
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: What you will do
- title: Drawing a line
  completion:
  - engaged
- title: Turning
- title: Changing colours
- title: Repetition
- title: Better spirals
  completion:
  - internal
- title: Loopy colours
- title: Modulo to the rescue
- title: Enormous lists
- title: Putting it all together
  completion:
  - external