---
title: अद्भुत Turtle
hero_image: images/banner.png
description: इस संसाधन में आप प्रोग्रामिंग भाषा Python के साथ अपना पहला कदम उठाएँगे
original_url: https://raspberrypi.org/learning/turtley-amazing
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: परिचय
- title: आपको किन चीजों की आवश्यकता होगी
- title: क्या यह कला, गणित, या कंप्यूटर विज्ञान है?
- title: एक रेखा खींचना
  completion:
  - engaged
- title: घुमाना
- title: रंग बदलना
- title: दोहराना
- title: बेहतर घुमावदार आकार
- title: लूपी रंग
- title: बचाव के लिए मॉड्यूलो
- title: भारी सूचियाँ
- title: इस सब को एक जगह लाना
  completion:
  - internal
- title: आगे क्या?
