---
title: Turtley Amazing
hero_image: images/banner.png
description: In this resource you will take your first steps with the programming language Python
original_url: https://raspberrypi.org/learning/turtley-amazing
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: taide
technologies: python
site_areas: projektit
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Johdanto
  - 
    title: Mitä tarvitset
  - 
    title: Is it art, maths, or computer science?
  - 
    title: Drawing a line
  - 
    title: Turning
  - 
    title: Changing colours
  - 
    title: Repetition
  - 
    title: Better spirals
  - 
    title: Loopy colours
  - 
    title: Modulo to the rescue
  - 
    title: Enormous lists
  - 
    title: Putting it all together
  - 
    title: What next?
