---
title: Impressionnante Tortue
hero_image: images/banner.png
description: Dans cette ressource, tu feras tes premiers pas avec le langage de programmation
  Python
original_url: https://raspberrypi.org/learning/turtley-amazing
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Ce dont tu auras besoin
- title: Est-ce de l'art, des mathématiques ou de l'informatique ?
- title: Tracer une ligne
  completion:
  - engaged
- title: Tourner
- title: Changer de couleurs
- title: Répétition
- title: De meilleures spirales
- title: Couleurs excentriques
- title: Modulo à la rescousse
- title: Listes énormes
- title: Récapitulons
  completion:
  - internal